/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v5.28.3
// source: proto/user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_user_pb from '../proto/user_pb';


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetUsers = new grpcWeb.MethodDescriptor(
    '/proto.UserService/GetUsers',
    grpcWeb.MethodType.UNARY,
    proto_user_pb.Empty,
    proto_user_pb.UsersResponse,
    (request: proto_user_pb.Empty) => {
      return request.serializeBinary();
    },
    proto_user_pb.UsersResponse.deserializeBinary
  );

  getUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null): Promise<proto_user_pb.UsersResponse>;

  getUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_user_pb.UsersResponse) => void): grpcWeb.ClientReadableStream<proto_user_pb.UsersResponse>;

  getUsers(
    request: proto_user_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_user_pb.UsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.UserService/GetUsers',
        request,
        metadata || {},
        this.methodDescriptorGetUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.UserService/GetUsers',
    request,
    metadata || {},
    this.methodDescriptorGetUsers);
  }

}

