FROM    node:16.14.2-alpine3.15

WORKDIR /app

COPY    ./server/package.json .

RUN     yarn
COPY    ./server/proto ./proto
COPY    ./proto ./proto
COPY    ./server/server.ts .

CMD ["yarn", "start"]

